/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

export const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://7fcsjk3fbngwvjaeicvomyxnni.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-63oekq56n5dd7led3mse2znziy",
    "aws_cognito_identity_pool_id": "us-east-1:b54205d9-518e-4bcb-b44f-9c77b343b73e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_9kzOhO7cc",
    "aws_user_pools_web_client_id": "96t9atnn8sm6lg08n4snqg2ab",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_cloud_logic_custom": [{
        "name": "usersAdmin",
        "endpoint": "https://nz8vshfeah.execute-api.us-east-1.amazonaws.com/master",
        "region": "us-east-1"
    }]
};


// export default awsmobile;
